### ISSUE TITLE
Deadlock in the E2E test when deleting the whole namespace

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#122]
When we have a namespace, in this case `dev` and we got a lot of stuffs there, says Terraform objects, Source objects, then we're trying to delete the whole namespace expecting all resources is cascaded deleted too.

The cluster stuck in this case because we didn't delete resources in backward order.
I'm not sure if there's a bug inside the controller, or it's a normal behaviour of Kubernetes.
This scenario happened with Flux as well when I was no-brainer trying to delete a namespace containing many Flux resources.

**Comment by chanwit** [comment]
@tomhuang12 does the above help?

**Comment by tomhuang12** [comment]
I think it's due to the CRDs have `finalizer` on them but the controller got deleted before finalizing is complete, therefore leaving the `finalizer` on those objects and preventing them from being deleted by the API server. I have observed the same with other controllers. [This](https://github.com/kubernetes/kubernetes/issues/60807#issuecomment-524772920) seems to be correct way to delete a namespace that's stuck.

**Comment by chanwit** [comment]
we now have a correct step to delete resources. closing.
