### ISSUE TITLE
Upgrade Terraform to 1.2.3

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#249]
The new version of Terraform has been released.
This 1.2.x series contains many significant changes and will break some of our test cases.

https://github.com/hashicorp/terraform/releases/tag/v1.2.3

**Comment by ekristen** [comment]
It might be better to look at supporting multiple or all versions of terraform programmatically. Since tfexec is already being used, this could do something like [tfswitch]() and look at the `versions.tf` for the maximum supported version of terraform and download and use it in real-time vs being hard-coded to a specific version of terraform. 

This would make the controller more dynamic and would allow the terraform code to control which version of terraform is used.

**Comment by ekristen** [comment]
@chanwit thoughts ^

**Comment by chanwit** [comment]
This is an incredible approach. I didn't think about that.

We would bundle multiple versions, say 0.1x, 1.1.x, and 1.2.x in the image and make it switchable via a soft link. What do you think?

**Comment by ekristen** [comment]
You can actually do this all from tfexec, if you add a bit of logic, you can have it download the necessary binary automatically and you don't need to engineer a soft link switch, and since this is already using tfexec, it shouldn't be too problematic to do.

**Comment by artem-nefedov** [comment]
But what about clusters with tight security, where you can only download stuff from private repos?
Will it support some form of authentication?

Just a thought here: how about re-using existing functionality of Flux's OCIRegistry source to allow user to get terraform binary from there?

**Comment by chanwit** [comment]
Closing this for now.
We'll support multiple TF binaries shortly.
