### ISSUE TITLE
Partial backend configuration clashes with `backendConfig.customConfiguration`

### ISSUE THREAD

**Issue by adamstrawson** [weaveworks/tf-controller#389]
Our Terraform modules use a partial configuration, which is recommended within the Terraform [documentation](https://www.terraform.io/language/settings/backends/configuration#partial-configuration) 

For example;

```
terraform {
  backend "gcs" {}
}
```

Locally, we use Terragrunt to populate the backend, and within cluster we use [/isaaguilar/terraform-operator](https://github.com/isaaguilar/terraform-operator) (which is what we're currently using, and hoping to migrate to `tf-controller`) `terraform-operator` supports the ability to pass a custom backend which replaces the partial configuration above. 

However, when setting the below example, tf-runner fails due to a duplicate backend. 

```
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: foo
  namespace: bar
spec:
  interval: 5m
  approvePlan: auto
  sourceRef:
    kind: GitRepository
    name: helloworld
    namespace: bar
  backendConfig:
    customConfiguration: |
        backend "gcs" {
          bucket = "terraform-state"
          prefix = "my-path"
          impersonate_service_account = "a-service-account
        }
```

tf-runner log for above resource:
```
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Duplicate backend configuration
 on main.tf line 2, in terraform:
 2: backend "gcs" {}

A module may have only one backend configuration. The backend was previously
configured at generated_backend_config.tf:3,3-16.
```

Does tf-controller not support partial configuration on backends, or is there an error in the documentation around how this should be formatted?

**Comment by chanwit** [comment]
Hi @adamstrawson 

Thank you for reporting the issue. We don't have a mechanism to support your use case yet.
But it's really a feature we would support. Maybe we would generate an override.tf instead?

**Comment by adamstrawson** [comment]
That would work @chanwit - I've submitted a PR (#392) with a solution for this issue.

**Comment by aristapimenta** [comment]
hi @adamstrawson, thanks for spotting and fixing this issue!

I'm currently working on a PoC and am trying to use tf-controller with GCS backend as well. could you pls provide more details or pointers on how do you do that via `impersonate_service_account`?

I'm currenty able to do something like this for authorizing the google terraform provider to manage GCP resources:

inside `main.tf`:
```hcl
variable "GOOGLE_CREDS" {
  type = string
}

provider "google" {
  project     = "project-id"
  credentials = var.GOOGLE_CREDS
}
```

then in `terraform.yaml` for `Terraform` object:

```yaml
  varsFrom:
  - kind: Secret
    name: tf-google-creds
```

then I have a `tf-google-creds` k8s secret with a base64-encoded JSON key for a GCP service account under the key `GOOGLE_CREDS` with the necessary permissions.

that works well for managing GCP resources, but something like the snippet below is not working very well for managing terraform state in GCS:

```hcl
  backend "gcs" {
    bucket      = "tf-cv-play-aeris"
    credentials = var.GOOGLE_CREDS
  }
```

because the `credentials` field of the `backend` block cannot pull input from variables:

```
Error: Variables not allowed

  on backend_override.tf line 5, in terraform:
   5:   credentials = var.GOOGLE_CREDS

Variables may not be used here.
```

any advices on the simplest way possible of using `tf-controller` with GCS backend?

**Comment by k0da** [comment]
```yaml
  backendConfig:
    customConfiguration: "backend \"s3\"{}"
  backendConfigsFrom:
  - kind: ConfigMap
    name: dev-mgmt-backend
```

This is how I configure S3 replace s3 with gcs and ConfigMap/Secret with key: values with gcs backend configuration

**Comment by chanwit** [comment]
GCS is quite tricky because you have to pass your environment variables directly to the pod via the spec's runner pod template.

**Comment by aristapimenta** [comment]
thanks @chanwit, but would `backendConfigsFrom` as suggested by @k0da also work? it definitely looks more elegant. similar to `varsFrom`, which looks like a great way to inject terraform variables.

**Comment by chanwit** [comment]
Yes, @k0da approach is cleaner and better.

**Comment by aristapimenta** [comment]
> Yes, @k0da approach is cleaner and better.

is there a way for me to debug this `bucket doesn't exist`? I'm pretty sure that the bucket exists because the `tf-runner` pod was previously able to create a `default.tfstate` object in that bucket which is still in there. I can see the log `mapping the Spec.BackendConfigsFrom`, is there a way for me to inspect the mapped values?

```
{"level":"info","ts":"2023-02-04T14:56:44.235Z","logger":"runner.terraform","msg":"preparing for Upload and Extraction","instance-id":""}
{"level":"info","ts":"2023-02-04T14:56:44.244Z","logger":"runner.terraform","msg":"write backend config","instance-id":"","path":"/tmp/tf-clusters-cv-play-aeris/terraform/clusters/cv-play-aeris","config":"backend_override.tf"}
{"level":"info","ts":"2023-02-04T14:56:44.244Z","logger":"runner.terraform","msg":"write config to file","instance-id":"","filePath":"/tmp/tf-clusters-cv-play-aeris/terraform/clusters/cv-play-aeris/backend_override.tf"}
{"level":"info","ts":"2023-02-04T14:56:44.245Z","logger":"runner.terraform","msg":"looking for path","instance-id":"","file":"terraform"}
{"level":"info","ts":"2023-02-04T14:56:44.246Z","logger":"runner.terraform","msg":"creating new terraform","instance-id":"ee5d934e-9523-4778-ba5b-eeb323896901","workingDir":"/tmp/tf-clusters-cv-play-aeris/terraform/clusters/cv-play-aeris","execPath":"/usr/local/bin/terraform"}
{"level":"info","ts":"2023-02-04T14:56:44.251Z","logger":"runner.terraform","msg":"setting envvars","instance-id":"ee5d934e-9523-4778-ba5b-eeb323896901"}
{"level":"info","ts":"2023-02-04T14:56:44.251Z","logger":"runner.terraform","msg":"getting envvars from os environments","instance-id":"ee5d934e-9523-4778-ba5b-eeb323896901"}
{"level":"info","ts":"2023-02-04T14:56:44.251Z","logger":"runner.terraform","msg":"setting up the input variables","instance-id":"ee5d934e-9523-4778-ba5b-eeb323896901"}
{"level":"info","ts":"2023-02-04T14:56:44.251Z","logger":"runner.terraform","msg":"mapping the Spec.Values","instance-id":"ee5d934e-9523-4778-ba5b-eeb323896901"}
{"level":"info","ts":"2023-02-04T14:56:44.251Z","logger":"runner.terraform","msg":"mapping the Spec.Vars","instance-id":"ee5d934e-9523-4778-ba5b-eeb323896901"}
{"level":"info","ts":"2023-02-04T14:56:44.251Z","logger":"runner.terraform","msg":"mapping the Spec.VarsFrom","instance-id":"ee5d934e-9523-4778-ba5b-eeb323896901"}
{"level":"info","ts":"2023-02-04T14:56:44.257Z","logger":"runner.terraform","msg":"generating the template founds"}
{"level":"info","ts":"2023-02-04T14:56:44.258Z","logger":"runner.terraform","msg":"main.tf.tpl not found, skipping"}
{"level":"info","ts":"2023-02-04T14:56:44.258Z","logger":"runner.terraform","msg":"initializing","instance-id":"ee5d934e-9523-4778-ba5b-eeb323896901"}
{"level":"info","ts":"2023-02-04T14:56:44.258Z","logger":"runner.terraform","msg":"mapping the Spec.BackendConfigsFrom","instance-id":"ee5d934e-9523-4778-ba5b-eeb323896901"}
{
  "terraform_version": "1.3.1",
  "platform": "linux_amd64",
  "provider_selections": {},
  "terraform_outdated": true
}

Initializing the backend...

Error: Failed to get existing workspaces: querying Cloud Storage failed: storage: bucket doesn't exist


{"level":"error","ts":"2023-02-04T14:56:44.800Z","logger":"runner.terraform","msg":"unable to initialize","instance-id":"ee5d934e-9523-4778-ba5b-eeb323896901","error":"exit status 1\n\nError: Failed to get existing workspaces: querying Cloud Storage failed: storage: bucket doesn't exist\n\n\n"}
{"level":"info","ts":"2023-02-04T14:56:44.802Z","logger":"runner.terraform","msg":"cleanup TmpDir","instance-id":"ee5d934e-9523-4778-ba5b-eeb323896901","tmpDir":"/tmp/tf-clusters-cv-play-aeris"}
```

this is the secret which I referenced in `backendConfigsFrom`:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: tf-backend-configs
  namespace: tf-clusters
data:
  bucket: base64(bucket-name)
  credentials: base64(GCP-SA-JSON-privete-key)
```

I wonder if I should not encode `bucket` in base64? :thinking:

**Comment by aristapimenta** [comment]
I found my problem. I base64-encoded the string `my-bucket\n`, with a line-break in the end. after I re-encoded it without the line-break the apply worked successfuly and I can finally see the resource inside the stare file stored in the GCS bucket. thanks!!!

**Comment by aristapimenta** [comment]
@chanwit do you think it makes to open an issue "setting bucket field in GCS backend config from secret base64-encoded with line-breaks breaks terraform". I just think it could be a nice-to-have fix because something like the shell command `echo my-bucket | base64` encodes `my-bucket\n` because of the behavior of `echo`, instead of `my-string`. I'd be also happy to contribute with the fix in case you think this use case should be supported

**Comment by ArieLevs** [comment]
@chanwit Hi

[controller docs](https://flux-iac.github.io/tofu-controller/use-tf-controller/with-a-custom-backend/) state that: 
```text
By default, TF-Controller uses the Kubernetes backend to store the Terraform state file (tfstate) in clusters.
```

Could you please assist to understand of why `customConfiguration` is needed in the first place, if
```hcl
terraform {
  backend "some backend" {
    ...
    ...
  }
}
```
already exists part of my TF code?

if not setting `backendConfig` at all, the controller totally ignores my terraform backend definition, i would expected a more native terraform way to pick the backend

**Comment by chanwit** [comment]
Normally the controller does not require you to declare your own backend block.

In your case, it works that way because the controller generates backend config as Terraform `_override` file. So it follows the semantics of config overriding from Terraform docs.

**Comment by ArieLevs** [comment]
@chanwit thanks for the quick response,

I've tracked the source code to this [API definition](https://flux-iac.github.io/tofu-controller/References/terraform/#infra.contrib.fluxcd.io/v1alpha2.BackendConfigSpec) and setting 
```yaml
backendConfig:
  disable: true
````
now makes the runner to use my already defined backend block, thanks!
(should the `disable` option be added to the [custom backend](https://flux-iac.github.io/tofu-controller/use-tf-controller/with-a-custom-backend/) documentation?, if yes I can add it part of an already opened PR)

The thing is that above definition will result the runner to `backend seems to be disabled completely, so there will be no plan output file`, later while using the branch planner there will be endless commits to git, since the planner fails with
```text
"error":"\nError: Failed to read the given file as a state or plan file\n\nState read error: Error loading statefile: open tfplan: no such file or\ndirectory\n\nPlan read error: open tfplan: no such file or directory\n"
```

This is a result from [here](https://github.com/flux-iac/tofu-controller/blob/main/controllers/tf_controller_plan.go#L55)
```go
// if backend is disabled completely, there will be no plan output file (req.Out = "")
if r.backendCompletelyDisable(terraform) {
  planRequest.Out = ""
}
```
is that a normal behavior ?

**Comment by chanwit** [comment]
`backend disable:true` is not for general use. It is a special for connecting to Terraform Cloud.

You would get uncertain behavior if you disable the backend but have your own defined in TF.

We might revisit this to improve backend semantics but it's less prioritized than rebooting the project and get a new release out.

**Comment by ArieLevs** [comment]
Thanks, opened a separate issue https://github.com/flux-iac/tofu-controller/issues/1238
