### ISSUE TITLE
Better observability / error logging

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#46]

**Comment by tomhuang12** [comment]
I am doing some research on how this is implemented in kustomize-controller. Looks like it's using [github.com/fluxcd/pkg/runtime/metrics](https://pkg.go.dev/github.com/fluxcd/pkg/runtime/metrics) which is already used in various places to record readiness and suspension. The only thing we are missing is recording duration like [this](https://github.com/fluxcd/kustomize-controller/blob/main/controllers/kustomization_controller.go#L252). 

I think I am missing a big piece here on what you guys are expecting for this issue. Any examples would be great! Thanks!

**Comment by phoban01** [comment]
I think this is largely related to code structure. The kustomize controller has very clear reconcile phases and the logging, metrics and events are consistent as a result. I think I might make sense to merge the multi-tenancy change first and then tackle this work, otherwise the sands could be shifting beneath our feet a little bit.
