### ISSUE TITLE
Add the Branch-Based Planner to the helm chart with a Feature Flag.

### ISSUE THREAD

**Issue by yitsushi** [weaveworks/tf-controller#580]
Acceptance criteria:
- [ ] There is a container image to ship the Branch-Based Planner.
- [ ] The Helm Chart has a field to enable the Branch-Based Planner (Feature Flag).

**Comment by yitsushi** [comment]
@chanwit @yiannistri : What do you think, which option would fit better?

* Option A has more tight integration and gives less work to the user as they don't have to install an extra chart.
* Option B has a much lower risk factor introducing issues to the chart and gives the user freedom to decide if they want to install the extra chart or not, but they lose the easy "enable one flag" option.

**Comment by yiannistri** [comment]
I would opt for A because that is simpler for a user to enable while this feature is in development. Having said that, this could be a useful flag to keep afterwards too (once we release this feature), if the user is not interested in enabling this feature and running 1 extra workload on their cluster for no reason.

**Comment by yitsushi** [comment]
Updated the description to use Option A (one chart only) and dropped Option B (separate charts)
