### ISSUE TITLE
Cleaning terraform-runner.tls secrets when this is outdated

### ISSUE THREAD

**Issue by mcortinas** [weaveworks/tf-controller#589]
Hi, 

 We're using tf-controller with several namespaces, basically one per use case. 
 I detected the runner is using a different TLS secret each day, one per day. 
 Let me open this issue in order to add to tf-controller the option/capability to clean the outdated k8s secrets not used.

 Let me attach an screenshot of one of our k8s namespaces after 7 days with a several k8s TLS secrets.
![image (5)](https://user-images.githubusercontent.com/692263/236416865-e3186a54-d112-48a7-9e9f-29dce7ece6d4.png)
 
Best,
Marc

**Comment by Nalum** [comment]
Have confirmed this with `v0.14.1` and resource in 1 namespace

**Comment by Nalum** [comment]
We've found the issue and are working to fix. Essentially it comes down to the GC on these TLS Secrets, the tf-controller currently maintains a list of Secrets that it holds in memory, once the Pod/Container is recreated/restarted that list is gone and Secrets are left around.

We are working to change this so that the list is taken from Kubernetes directly, so on startup any existing TLS Secrets will be cleaned out and going forward for the life of the Pod/Container at renewal time a check will be run that will clean out any TLS Secrets no longer needed. This should hopefully fix this issue and also clean up the issue for anyone who upgrades but has not noticed before hand.

**Comment by mcortinas** [comment]
Apologies due to I couldn't answer before. Happy to help and very good job with this fix , it seems the best approach. Thank you!

**Comment by chanwit** [comment]
@mcortinas we have a new image for you to try:
ghcr.io/weaveworks/tf-controller:gc-old-certs-86395477

Please use the `rc.yaml` and replace image tags to be: `gc-old-certs-86395477`.
