### ISSUE TITLE
Handle the list of Pull Requests

### ISSUE THREAD

**Issue by yitsushi** [weaveworks/tf-controller#662]
* Query existing branch-based planner Terraform objects.
* If there is no existing Terraform object create one (clone from the original one with changed fields: Terraform and Source).
* Save the ID of the PR and the latest commit hash on the Terraform object.

**Comment by squaremo** [comment]
I think you will want to set an OwnerRef, too, so you can go back and find all the objects that _shouldn't_ exist (any more).

**Comment by opudrovs** [comment]
@squaremo ok, thanks. Can you please elaborate a bit to what values (objects) the OwnerRef should be set to and on which objects?

For example, should it be set on the planner TF objects (each corresponding to a PR) to the original TF object (so that if that original object is deleted all planner TF objects cloned from the original TF object are garbage collected/deleted too)?

Or should it be set on the planner TF objects or GitRepositories corresponding to them and to which value?

**Comment by squaremo** [comment]
> Can you please elaborate to what values (objects) the OwnerRef should be set to and on which objects?

A typical scheme for a reconciler loop is, given a "cause" object (in this case, the original Terraform object):

 1. Calculate all the objects that should exist (e.g., in this case a Terraform object and source for each PR on the relevant repo);
 1a. Set an owner reference on each, identifying the "cause" for its creation;
 2. Update or insert each of those objects as needed;
 3. Get a list of all objects that are owned by the cause object;
 4. Delete any of those that aren't part of the set calculated in 1.

Owner references have garbage collection implications that need to be carefully considered: https://kubernetes.io/docs/concepts/architecture/garbage-collection/ (these do roughly fit this situation: if the original Terraform object is deleted, you would want all its branch planning objects to also be deleted).

**Comment by opudrovs** [comment]
Interesting, thank you!
