### ISSUE TITLE
Support different types for outputs/inputs

### ISSUE THREAD

**Issue by Smana** [weaveworks/tf-controller#678]
Hi there,

I'm trying to pass a list of string from a module to another.
From my understanding [this change](https://github.com/weaveworks/tf-controller/pull/504) should have fixed the issue, however in my case I get this error:

```console
Error: Invalid value for input variable

  on generated.auto.tfvars.json line 1:
   1: {"cluster_name":"dev-0","env":"dev","github_owner":"Smana","github_repository":"demo-tf-controller","github_token":"xxx","private_subnets":"[\n      \"subnet-xxx\",\n      \"subnet-xxx\",\n      \"subnet-xxx\"\n    ]","vpc_id":"vpc-xxx"}

The given value is not suitable for var.private_subnets declared at
variables.tf:19,1-27: list of string required.
```

Did I miss something? Is there a parameter to add to specify the expected type?

Helm chart version: 0.12.0
tf-controller version: v0.15.0-rc.1

Regards,

**Comment by Nitin0072** [comment]
Hi Team,

I am also facing the same issue. Faced this issue while Output from another module need to be consumed in current module. If the output is string then there is no issue , but when the output is a complex data structure like list or map , then output secret is storing those in string format and also when consumed it acts as string because of which terraform gives error "Invalid Value of Input Variable"

I am using TF Controller : 0.14.0

**Parent Module** 
Terraform Object
` writeOutputsToSecret:
    name: base-infra-output`

output.tf
`
.....
....
output "dummy" {
  value = ["a","b","c"]
}
`

**Current/Child/Consumer Module**
Terraform Object
`varsFrom:
  - kind: Secret
    name: base-infra-output`

main.tf
`
terraform {
  required_version = ">= 1.1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

variable "dummy" {
  type = list(string)
}

variable "access_key" {
  type = string
}
variable "secret_key" {
  type = string
}

provider "aws" {
  region = "eu-west-3"
  access_key = var.access_key
  secret_key = var.secret_key
}

output "consumer-output" {
  value = var.dummy
}
`
 
Error
`"error":"error running Plan: rpc error: code = Internal desc = exit status 1\n\nError: Invalid value for input variable\n\n  on generated.auto.tfvars.json line 1:\n   1: {\"access_key\":\"<****>\",\"dummy\":\"[\\n      \\\"a\\\",\\n      \\\"b\\\",\\n      \\\"c\\\"\\n    ]\",\"dummy.type\":\"[\\n      \\\"tuple\\\",\\n      [\\n        \\\"string\\\",\\n        \\\"string\\\",\\n        \\\"string\\\"\\n      ]\\n    ]\",\"secret_key\":\"<*****>\"}\n\nThe given value is not suitable for var.dummy declared at\nvariables.tf:1,1-17: list of string required.\n"}`

**Comment by Smana** [comment]
Now that [this issue](https://github.com/weaveworks/tf-controller/issues/712) is fixed, it becomes harder to understand that my error is caused by the type of the variable.

```console
flux-system     eks-dev-0                       False   error running Plan: rpc error: code = Internal desc = exit status 1                                                                                     false           1 hour
                                                                                                                                                                                                                                      
                                                        Error: Invalid value for input variable                                                                                                                                       
                                                                                                                                                                                                                                      
                                                          on generated.auto.tfvars.json line 1:                                                                                                                                       
                                                           1: {"cluster_name":"***","env":"***","github_owner":"***","github_repository":"***","github_token":"***","private_subnets":"***","vpc_id":"***"}                           
                                                                                                                                                                                                                                      
                                                        The given value is not suitable for var.private_subnets declared at                                                                                                           
                                                        variables.tf:19,1-27: list of string required.
```

**Comment by chanwit** [comment]
Exactly. We had to cope with sensitive information first. The the top priority.

From my tests as well as your logs, the error message is still relevant and understandable, for example:

```
The given value is not suitable for var.private_subnets declared at                                                                                                           
variables.tf:19,1-27: list of string required.
```

I'll address this output/input issue ASAP after the Flux v2 GA is launched.

**Comment by LappleApple** [comment]
Resolved.
