### ISSUE TITLE
Should the branch-based planner be included in the main controller?

### ISSUE THREAD

**Issue by squaremo** [weaveworks/tf-controller#690]
At present the branch-based planner (#576) exists as a stand-alone binary; but, it should be deployable to a cluster. The question is, then: should it be its own controller (deployment), or should it just be included in the tf-controller manager and deployed with it?

~I will draft an RFC~ (EDIT: I have no definitive answer to offer in an RFC)
I started a discussion about it: https://github.com/weaveworks/tf-controller/discussions/722

**Comment by LappleApple** [comment]
Depends partly on our strategy for branch-based planner.

**Comment by LappleApple** [comment]
From @Nalum: Split between controller and runner makes sense, but the branch planner should be part of the controller itself.

@madAndroid +1 for reducing divergence. Instead of having three components to execute the change, you should run the same binary for branch planner as the runner (as they're the same).

**Comment by LappleApple** [comment]
The team has decided to include it in the main controller. Any related work would take place after critical resource deletion mechanism issues are resolved.
