### ISSUE TITLE
Test 230 and 140 fail consistently

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#78]
Just the only test case I've seen failing repeatedly across job runs. Need a proper way to fix it.

**Comment by tomhuang12** [comment]
Test 140 has the same issue.

**Comment by chanwit** [comment]
updated

**Comment by phoban01** [comment]
I believe this is happening because we have a variable shadowing problem in the drift detection block:
https://github.com/weaveworks/tf-controller/blob/eb1bd17016516d061657adf5a0a63e84eeff8de1/controllers/terraform_controller.go#L582-L606

If we want to keep these variables names it should read:
```golang
if r.shouldDetectDrift(terraform, revision) {
	var driftDetectionErr error // declared here to avoid shadowing on terraform variable
	terraform, driftDetectionErr = r.detectDrift(ctx, terraform, tfInstance, runnerClient, revision)
...
``` 
If we passed a pointer to the `detectDrift` method then we would also avoid this issue; that would involve changing the code in quite a few areas but might be worth it. 

Any thoughts @chanwit?

**Comment by chanwit** [comment]
This is making sense because it's happening only with tests related to the drift detection.
